apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "false"
  labels:
    app: guestbook-chris
  name: guestbook-chris
  namespace: cbourgeois1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-chris
  strategy: {}
  template:
    metadata:
      labels:
        app: guestbook-chris
    spec:
      containers:
      - image: cbourgeois1/guestbook:1.0
        name: guestbook
